# This workflow will upload a Python Package using the PyPi action workflow

name: Upload Python Package

on:
  release:
    types: [published]

env:
  SKIP_GENERATE_AUTHORS: 1
  SKIP_WRITE_GIT_CHANGELOG: 1

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
       py_version: ["3.9"] 
          
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py_version }}
    - name: Install dependencies
      run: |
        pip install --upgrade setuptools pip
    - name: Install package and requirements
      run: |
        pip install --upgrade .
        pip install -r requirements-tests.txt
    - name: Run pytest with codecoverage
      run: |
        coverage run --source=hypothesis_networkx $(which pytest) --hypothesis-show-statistics
        coverage report
        codecov
       
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
        pip install pbr
         
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master      
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

